// githubRepoCreator.js
const axios = require('axios');
require('dotenv').config();

/**
 * GitHub に新しいリポジトリを作成して、clone URL を返します。
 */
async function createNewRepository(repoName) {
  const url = 'https://api.github.com/user/repos';
  const payload = {
    name: repoName,
    description: `${repoName} generated by GPT`,
    private: false
  };
  const headers = {
    // ← ここを "token" スキームに
    Authorization: `token ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github.v3+json'
  };

  const res = await axios.post(url, payload, { headers });
  return res.data.clone_url;
}

module.exports = { createNewRepository };
